### PR TITLE
Fix arm rclone build

### PR DESCRIPTION
**Pull request by escoand**
Fix the rclone build on arm.

Reference: https://github.com/nodejs/node/issues/4212#issuecomment-217904671

### CODE REVIEW

**Comment by escoand** [comment]
The problem does not occur in your drone build before merge because of this

https://github.com/djmaze/resticker/blob/641778fc50d27fe26f5ee4de88b56ad6d33aea2f/.drone.yml#L19-L22

**Comment by djmaze** [comment]
@escoand Could you please merge the latest master? I adjusted the drone configuration so it will try to build images for PRs like this as well. Then we can see if everything is working.

**Comment by escoand** [comment]
OK, build seems to work but there is no way to pull this containers. Not a problem but something I recognized.

**Comment by djmaze** [comment]
Okay, I thought about this and changed it so that now an image is built for every PR. Just merge master again and we can try it out directly ;)

**Comment by djmaze** [comment]
Hmm.. This seems to be broken somehow ;-/

```bash
$ docker run -it --rm --entrypoint sh mazzolino/restic-test:pr-68-arm64
/ # rclone
Segmentation fault (core dumped)
```

Same with the arm32 image (`mazzolino/restic-test:pr-68-arm`).

**Comment by escoand** [comment]
I can verify the problem on arm as well, but...
```bash
$ docker run -it --rm --entrypoint rclone mazzolino/restic-test:pr-68-arm version
standard_init_linux.go:207: exec user process caused "exec format error"

$ docker build -qt mytest https://github.com/escoand/resticker.git#patch-1 && docker run -it --rm --entrypoint rclone mytest version
rclone v1.53.3-DEV
- os/arch: linux/arm
- go version: go 1.15.6
```

I've compared the previous build for arm https://ci.strahlungsfrei.de/djmaze/resticker/141/2/2
```
+ /usr/local/bin/docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:20 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:44:51 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

with the last not working build https://ci.strahlungsfrei.de/djmaze/resticker/160/2/2:
```
+ /usr/local/bin/docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:06 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:28:48 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

As you can see the `OS/Arch` switched from `linux/arm` to `linux/arm64`. Was this by intention?

**Comment by escoand** [comment]
For arm64 I can't find a problem, but I have no hardware to test the build in general.

**Comment by djmaze** [comment]
Well, it is a bit embarassing, but the drone configuration was still not correct. I fixed it in #71. Could you please merge again? Then the arm build should at least be generally working.

**Comment by djmaze** [comment]
I just built rclone manually inside the docker image on my arm64 machine. I still got the segfault when compiling with `go build`.

However, if I do a static build, it works! Maybe we should just change it?

```bash
CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' .
```

**Comment by djmaze** [comment]
Both arm and arm64 work for me now. Great, thanks for your patience! :)

**Comment by escoand** [comment]
Also thanks to you!

**Pull request merged**
