### PR TITLE
Update alpine to 3.9

### PR DESCRIPTION
**Pull request by jlelse**

### CODE REVIEW

**Comment by djmaze** [comment]
Thanks.

**Comment by jlelse** [comment]
Your CI seems to be broken :thinking: Pushing the template doesn't seem to work.

**Comment by jlelse** [comment]
And a question: Would you accept a PR adding a feature for pre-backup commands? I modified the code to be able to execute docker commands prior to backup, so I can do a database dump etc. It works perfectly, but adds the docker-cli package to the image and one needs to mount the docker socket for the use of this feature.

**Comment by djmaze** [comment]
> Your CI seems to be broken

Well, it is configured to just build git tags, because I am tagging commits according to the restic version they install. Not sure if a different versioning might make more sense..

**Comment by djmaze** [comment]
> And a question: Would you accept a PR adding a feature for pre-backup commands?

Not sure I like to extend the container's privileges _that much_. Personally, I am thinking about disabling the built-in cron and using [swarm-cronjob](https://github.com/crazy-max/swarm-cronjob) for scheduling instead. Then, for pre-backup purposes, you could schedule a different service with enough time buffer so it is finished when the backup service is scheduled. 

From a separation of concerns standpoint, that would be the cleaner approach. Of course, that only works in swarm mode. Would that be feasible for you?

**Comment by jlelse** [comment]
@djmaze I'm using docker-compose (without swarm), so removing the built-in cron would mean I would need to create my own docker file.

Regarding the Docker-CLI thing, I will create a PR and we can discuss things further.

**Pull request merged**
