### PR TITLE
Update rclone and restic

### PR DESCRIPTION
**Pull request by jlelse**
Restic released the update with much faster prune performance.

### CODE REVIEW

**Comment by djmaze** [comment]
The new alpine version seems to break the arm build, and it looks like fixing that might take some time (which I might have at weekend at the earliest). @jlelse Would you mind downgrading alpine to the old version again?

Not doing the alpine upgrade right now seems to be a quick fix so we can get the new release out. Agreed?

**Comment by jlelse** [comment]
@djmaze The logs look like a temporary TLS failure with the Alpine CDN. Maybe it already helps to just re-run the test?

**Comment by escoand** [comment]
Is it maybe the same problem I had with the alpine images?
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements

**Comment by djmaze** [comment]
@escoand Yes, and we do not have a 19.03.9 docker-in-docker image for arm since [the builds are broken for more than half a year now](https://github.com/docker-library/docker/issues/260). So we can't build this stuff in drone currently.

**Comment by djmaze** [comment]
Merging this since it now builds correctly.

**Comment by jlelse** [comment]
Maybe we should switch to just using the provided binaries instead of building everything from source? restic as well as rclone provide binaries for all supported platforms.

**Comment by djmaze** [comment]
@jlelse Sorry for the late answer. Yeah, that would be possible. I am open to that change.

**Comment by djmaze** [comment]
I added an issue for that: #84

**Pull request merged**
