### PR TITLE
Introduce `ENABLE_JSON_LOGGING`

### PR DESCRIPTION
**Pull request by jeankhawand**
This change adds the `ENABLE_JSON_LOGGING` option to export restic metadata in JSON format. The goal is to improve restic logs accessibility by allowing users to utilize tools like `jq` to process the metadata. This enables users to create external scripts for extracting metadata and sending notifications using `run_commands`.

update doc and include notify script as sample to send backup metadata via apprise

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Hey @jeankhawand,
In case you didn't see it before, this is slightly related to https://github.com/djmaze/resticker/issues/181
Feel free to share your opinion over there :)
Thanks for the PR!

**Comment by escoand** [comment]
How do you pass the variable log file name to the notify script?

**Comment by jeankhawand** [comment]
image

**Comment by jeankhawand** [comment]
> How do you pass the variable log file name to the notify script?

good catch, I missed exporting it!

**Pull request closed without merging**
